"""crear tabla costos materiales reales

Revision ID: 1a407099a747
Revises: e23147533407
Create Date: 2026-09-10 22:29:32.363514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a407099a747'
down_revision: Union[str, Sequence[str], None] = 'e23147533407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costos_materiales_reales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['material_cotizacion_id'], ['materiales_cotizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costos_materiales_reales')
    # ### end Alembic commands ###
