"""agregar_es_test_y_ultimo_cambio_a_usuarios

Revision ID: 4bb7128bc4d5
Revises: afa6caea0be9
Create Date: 2026-09-20 20:23:49.741079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb7128bc4d5'
down_revision: Union[str, Sequence[str], None] = 'afa6caea0be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('es_test', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('usuarios', sa.Column('ultimo_cambio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ultimo_cambio')
    op.drop_column('usuarios', 'es_test')
    # ### end Alembic commands ###
