"""Cambiar descripcion a Text

Revision ID: 57204b8d0ffa
Revises: 85f70cd54c44
Create Date: 2026-09-20 21:21:47.996453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57204b8d0ffa'
down_revision: Union[str, Sequence[str], None] = '85f70cd54c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidas_cotizacion', 'descripcion',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidas_cotizacion', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###
