"""Add usuario_id and es_test to ImpuestoMensual

Revision ID: 7a169f8a6b19
Revises: 9725e953c909
Create Date: 2026-09-21 01:15:59.857752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a169f8a6b19'
down_revision: Union[str, Sequence[str], None] = '9725e953c909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impuestos_mensuales', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('impuestos_mensuales', sa.Column('es_test', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('uq_impuestos_mensuales_año_mes'), 'impuestos_mensuales', type_='unique')
    op.create_foreign_key(None, 'impuestos_mensuales', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'impuestos_mensuales', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_impuestos_mensuales_año_mes'), 'impuestos_mensuales', ['año', 'mes'], postgresql_nulls_not_distinct=False)
    op.drop_column('impuestos_mensuales', 'es_test')
    op.drop_column('impuestos_mensuales', 'usuario_id')
    # ### end Alembic commands ###
