"""Add usuario_id and es_test for data isolation

Revision ID: 9725e953c909
Revises: 57204b8d0ffa
Create Date: 2026-09-21 01:05:14.992967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9725e953c909'
down_revision: Union[str, Sequence[str], None] = '57204b8d0ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('es_test', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'clientes', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('cotizaciones', sa.Column('es_test', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('materiales', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('materiales', sa.Column('es_test', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'materiales', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('proyectos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('proyectos', sa.Column('es_test', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'proyectos', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('ventas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('ventas', sa.Column('es_test', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'ventas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_column('ventas', 'es_test')
    op.drop_column('ventas', 'usuario_id')
    op.drop_constraint(None, 'proyectos', type_='foreignkey')
    op.drop_column('proyectos', 'es_test')
    op.drop_column('proyectos', 'usuario_id')
    op.drop_constraint(None, 'materiales', type_='foreignkey')
    op.drop_column('materiales', 'es_test')
    op.drop_column('materiales', 'usuario_id')
    op.drop_column('cotizaciones', 'es_test')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'es_test')
    op.drop_column('clientes', 'usuario_id')
    # ### end Alembic commands ###
