"""Add foto_perfil to Usuario

Revision ID: a2847d08dbec
Revises: af105a0d3529
Create Date: 2026-09-26 18:55:38.693592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2847d08dbec'
down_revision: Union[str, Sequence[str], None] = 'af105a0d3529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('foto_perfil', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'foto_perfil')
    # ### end Alembic commands ###
