"""relacionar componentes con partidas

Revision ID: aec4c16fb2c0
Revises: c193b700568c
Create Date: 2026-09-11 16:30:12.761264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec4c16fb2c0'
down_revision: Union[str, Sequence[str], None] = 'c193b700568c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos_extra_cotizados', sa.Column('partida_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('gastos_extra_cotizados_cotizacion_id_fkey'), 'gastos_extra_cotizados', type_='foreignkey')
    op.create_foreign_key(None, 'gastos_extra_cotizados', 'partidas_cotizacion', ['partida_id'], ['id'])
    op.drop_column('gastos_extra_cotizados', 'cotizacion_id')
    op.add_column('mano_obra_cotizada', sa.Column('partida_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('mano_obra_cotizada_cotizacion_id_fkey'), 'mano_obra_cotizada', type_='foreignkey')
    op.create_foreign_key(None, 'mano_obra_cotizada', 'partidas_cotizacion', ['partida_id'], ['id'])
    op.drop_column('mano_obra_cotizada', 'cotizacion_id')
    op.add_column('materiales_cotizacion', sa.Column('partida_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('materiales_cotizacion_cotizacion_id_fkey'), 'materiales_cotizacion', type_='foreignkey')
    op.create_foreign_key(None, 'materiales_cotizacion', 'partidas_cotizacion', ['partida_id'], ['id'])
    op.drop_column('materiales_cotizacion', 'cotizacion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiales_cotizacion', sa.Column('cotizacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'materiales_cotizacion', type_='foreignkey')
    op.create_foreign_key(op.f('materiales_cotizacion_cotizacion_id_fkey'), 'materiales_cotizacion', 'cotizaciones', ['cotizacion_id'], ['id'])
    op.drop_column('materiales_cotizacion', 'partida_id')
    op.add_column('mano_obra_cotizada', sa.Column('cotizacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mano_obra_cotizada', type_='foreignkey')
    op.create_foreign_key(op.f('mano_obra_cotizada_cotizacion_id_fkey'), 'mano_obra_cotizada', 'cotizaciones', ['cotizacion_id'], ['id'])
    op.drop_column('mano_obra_cotizada', 'partida_id')
    op.add_column('gastos_extra_cotizados', sa.Column('cotizacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gastos_extra_cotizados', type_='foreignkey')
    op.create_foreign_key(op.f('gastos_extra_cotizados_cotizacion_id_fkey'), 'gastos_extra_cotizados', 'cotizaciones', ['cotizacion_id'], ['id'])
    op.drop_column('gastos_extra_cotizados', 'partida_id')
    # ### end Alembic commands ###
