"""Add AnexoFotografico

Revision ID: af105a0d3529
Revises: e7066ec04e23
Create Date: 2026-09-21 17:33:18.251703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af105a0d3529'
down_revision: Union[str, Sequence[str], None] = 'e7066ec04e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos_fotograficos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('ruta_imagen', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexos_fotograficos_id'), 'anexos_fotograficos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anexos_fotograficos_id'), table_name='anexos_fotograficos')
    op.drop_table('anexos_fotograficos')
    # ### end Alembic commands ###
