"""crear tabla impuestos mensuales

Revision ID: c193b700568c
Revises: 50b481eb3624
Create Date: 2026-09-10 22:50:36.956188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c193b700568c'
down_revision: Union[str, Sequence[str], None] = '50b481eb3624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impuestos_mensuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('año', 'mes', name='uq_impuestos_mensuales_año_mes')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impuestos_mensuales')
    # ### end Alembic commands ###
