"""agregar iva a ventas

Revision ID: cf7ed5a79eb4
Revises: aec4c16fb2c0
Create Date: 2026-09-11 19:08:47.019367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7ed5a79eb4'
down_revision: Union[str, Sequence[str], None] = 'aec4c16fb2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'ventas',
        sa.Column(
            'iva',
            sa.Numeric(precision=12, scale=2),
            nullable=True
        )
    )

    op.execute(
        "UPDATE ventas SET iva = subtotal * 0.16"
    )

    op.alter_column(
        'ventas',
        'iva',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'iva')
    # ### end Alembic commands ###
