"""Add Notas Importantes

Revision ID: e7066ec04e23
Revises: 7a169f8a6b19
Create Date: 2026-09-21 17:11:18.944808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7066ec04e23'
down_revision: Union[str, Sequence[str], None] = '7a169f8a6b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_importantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('es_test', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cotizaciones', sa.Column('nota_importante_id', sa.Integer(), nullable=True))
    op.add_column('cotizaciones', sa.Column('nota_importante_texto', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'cotizaciones', 'notas_importantes', ['nota_importante_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_column('cotizaciones', 'nota_importante_texto')
    op.drop_column('cotizaciones', 'nota_importante_id')
    op.drop_table('notas_importantes')
    # ### end Alembic commands ###
