"""agregar fk venta a costos materiales reales

Revision ID: f830070f1658
Revises: 325165084540
Create Date: 2026-09-11 19:45:42.302385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f830070f1658'
down_revision: Union[str, Sequence[str], None] = '325165084540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'costos_materiales_reales', 'ventas', ['venta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'costos_materiales_reales', type_='foreignkey')
    # ### end Alembic commands ###
