name: Deploy Mancore API

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Actualizar código
        run: |
          cd ~/mancoreapi
          git fetch origin
          git reset --hard origin/main

      - name: Reconstruir API
        run: |
          cd ~/mancoreapi
          docker compose up -d --build api

      - name: Verificar API
        run: |
          cd ~/mancoreapi
          docker compose ps api
          docker ps --filter "name=mancore-api"
